# Generated by Django 4.2.7 on 2023-12-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "about",
                    models.TextField(default="Explain about book here", max_length=500),
                ),
                ("author", models.CharField(max_length=70)),
                ("pub_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fiction", "Fiction"),
                            ("Novel", "Novel"),
                            ("Narrative", "Narrative"),
                            ("Mystery", "Mystery"),
                            ("Sci-Fi", "Science Fiction"),
                            ("Fantasy", "Fantasy"),
                            ("Thriller", "Thriller"),
                            ("History", "History"),
                            ("Memoir", "Memoir"),
                            ("Humor", "Humor"),
                        ],
                        max_length=25,
                    ),
                ),
                ("avg_rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField(max_length=1000)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=1,
                    ),
                ),
                ("user", models.CharField(default="Anonymous", max_length=20)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ReviewHub.book"
                    ),
                ),
            ],
        ),
    ]
