# Generated by Django 4.2.7 on 2023-12-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=70)),
                ("pub_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fiction", "Fiction"),
                            ("Novel", "Novel"),
                            ("Narrative", "Narrative"),
                            ("Mystery", "Mystery"),
                            ("Sci-Fi", "Science Fiction"),
                            ("Fantasy", "Fantasy"),
                            ("Thriller", "Thriller"),
                            ("History", "History"),
                            ("Memoir", "Memoir"),
                            ("Humor", "Humor"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
