# Generated by Django 4.2.7 on 2023-12-24 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ReviewHub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
