# Generated by Django 4.2.7 on 2023-12-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReviewHub", "0002_user_book_about_book_avg_rating_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="avg_rating",
        ),
    ]
