# Generated by Django 4.2.7 on 2023-12-23 14:47

import ReviewHub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReviewHub", "0003_remove_book_avg_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="book",
            name="avg_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="username",
            field=models.CharField(
                default="Anonymous",
                max_length=20,
                validators=[ReviewHub.models.validate_username],
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
